/**
 * Every automated message this product sends, in one list.
 *
 * This file is the answer to "which message goes to whom", and it exists
 * because that answer was previously spread across nine edge functions, four
 * database triggers, nineteen crons and a Kotlin view-model — so the only way
 * to know whether the booking alert had fired was to read source and then
 * query the database by hand.
 *
 * It is deliberately a hand-maintained registry rather than something derived
 * from the code. There is no honest way to introspect "what does this cron
 * eventually send"; pretending otherwise would produce a screen that is
 * confidently wrong. A stale entry here is visible and fixable — a missing one
 * is a message nobody is watching, so ADD TO THIS LIST when you add a message.
 *
 * `statusKind` is how a row finds its own history:
 *   wa:<kind>   → whatsapp_messages.kind, stamped by _shared/notify.ts
 *   activity    → lead_activities, for reminders
 *   none        → nothing is recorded anywhere (see `blind`)
 */

export type Audience = "founder" | "telecaller" | "customer";

export type Automation = {
  id: string;
  audience: Audience;
  name: string;
  /** What makes it fire, in words a person can check. */
  trigger: string;
  /** The pipe it actually leaves by. */
  channel: "WhatsApp" | "FCM push" | "In-app" | "Device WhatsApp";
  /** Which WhatsApp account carries it, when it is WhatsApp. */
  sender?: string;
  /** The function or file that sends it. */
  sentBy: string;
  /** Where the words live. */
  template: string;
  /** How this row finds its last send. */
  statusKind: string | null;
  /** Set when nothing at all is logged — stated rather than hidden. */
  blind?: string;
  /** A truth about the status line that would otherwise mislead. */
  caveat?: string;
  /** A safe way to fire one now, if there is one. */
  test?: { kind: "pulse" | "alert"; label: string; note: string };
  /** The message as it actually reads. Kept beside the template path so the
   *  two are corrected together. */
  preview: string;
  /** Where a live, real-data preview already exists. */
  livePreview?: { href: string; label: string };
};

export const AUTOMATIONS: Automation[] = [
  // ─────────────────────────── FOUNDER ───────────────────────────
  {
    id: "alert-site-visit-fixed",
    audience: "founder",
    name: "Site visit fixed",
    trigger: "A lead gets a site_visit_at in the future · checked every 15 min",
    channel: "WhatsApp",
    sender: "Baileys (platform number), falls back to Meta",
    sentBy: "founder-alerts",
    template: "supabase/functions/founder-alerts/index.ts",
    statusKind: "wa:alert",
    test: {
      kind: "alert",
      label: "Run the alert sweep now",
      note: "Ignores quiet hours. Only sends milestones not already logged — it cannot re-send one.",
    },
    preview: `📍 SITE VISIT FIXED

👤 Customer: Sonu Aazmi
👩 Executive: Shweta
📍 Project: Manas Property
📅 Visit: 5 Aug, 11:00 AM

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "alert-booking",
    audience: "founder",
    name: "Booking confirmed",
    trigger: "Lead status becomes booked · checked every 15 min",
    channel: "WhatsApp",
    sender: "Baileys (platform number), falls back to Meta",
    sentBy: "founder-alerts",
    template: "supabase/functions/founder-alerts/index.ts",
    statusKind: "wa:alert",
    preview: `🎉 BOOKING CONFIRMED

👤 Customer: Krishanpal Singh
👩 Executive: Shweta
📍 Project: Manas Property
💰 Booking amount: ₹50,000

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "alert-payment",
    audience: "founder",
    name: "Payment received",
    trigger: "Status token_paid with an amount · checked every 15 min",
    channel: "WhatsApp",
    sender: "Baileys (platform number), falls back to Meta",
    sentBy: "founder-alerts",
    template: "supabase/functions/founder-alerts/index.ts",
    statusKind: "wa:alert",
    preview: `🏆 PAYMENT RECEIVED

👤 Customer: Krishanpal Singh
👩 Executive: Shweta
📍 Project: Manas Property
💰 ₹2.5L

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "alert-visit-done",
    audience: "founder",
    name: "Site visit completed",
    trigger: "Customer arrived and no outcome recorded · every 15 min",
    channel: "WhatsApp",
    sender: "Baileys (platform number), falls back to Meta",
    sentBy: "founder-alerts",
    template: "supabase/functions/founder-alerts/index.ts",
    statusKind: "wa:alert",
    preview: `✅ SITE VISIT COMPLETED

👤 Customer: Krishanpal Singh
👩 Executive: Shweta
🎯 Feedback call within 24 hours — decision abhi pending hai.

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "pulse-team",
    audience: "founder",
    name: "Daily Pulse — whole team",
    trigger: "Hourly cron; sends to recipients whose chosen hour is now (IST)",
    channel: "WhatsApp",
    sender: "Baileys (platform number), falls back to Meta",
    sentBy: "pulse-broadcast",
    template: "pulseText() · supabase/functions/_shared/pulse.ts",
    statusKind: "wa:pulse",
    test: {
      kind: "pulse",
      label: "Send now",
      note: "Sends tonight's real report immediately to that one recipient.",
    },
    livePreview: { href: "/dashboard/pulse", label: "See today's real text on Daily Pulse" },
    preview: `📊 Manas property · Daily Pulse
Tue, 4 Aug

🟢 Today
• Bookings: 1
• Token collected: ₹50,000
• Site visits fixed: 2
• Hot leads: 10
• Calls: 8 · connected 7 (88%) · 11m talk
• Visit rate: 29% of everyone talked to

━━━━━━━━━━━━━━━
👤 Shweta
8 calls | 7 (88%) connected | 🔥 10 hot | 🎉 1 booked ₹50,000
✅ Sonu Aazmi committed to a site visit within 2 days.
🔸 Krishanpal Singh has visited but no feedback yet.
🎯 Next: Naseer Mohd — 3:44 PM

Auto Generated by Call Pro AI • Executive Intelligence`,
  },

  // ────────────────────────── TELECALLER ──────────────────────────
  {
    id: "pulse-own",
    audience: "telecaller",
    name: "Own Daily Pulse",
    trigger: "Same hourly cron, for recipients with a salesperson_id",
    channel: "WhatsApp",
    sender: "Baileys (platform number)",
    sentBy: "pulse-broadcast",
    template: "repText() · supabase/functions/_shared/pulse.ts",
    statusKind: "wa:pulse",
    test: {
      kind: "pulse",
      label: "Send now",
      note: "Their own day only — never the team roll-up.",
    },
    livePreview: { href: "/dashboard/pulse", label: "Per-rep card on Daily Pulse" },
    preview: `📊 Shweta | Daily Pulse | Tue, 4 Aug
Manas property

🟢 Today
• Bookings: 0
• Site visits fixed: 2
• Hot leads: 10
• Calls: 8 · connected 7 (88%) · 11m talk

🎯 Biggest win
✅ Sonu Aazmi committed to a site visit within 2 days.

🎯 Priority next
• Naseer Mohd — 3:44 PM

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "rep-coach",
    audience: "telecaller",
    name: "Rep Coach — 7pm review",
    trigger: "Assistant tick after the review hour, once a day",
    channel: "In-app",
    sentBy: "rep-coach → AssistantPrompts.kt",
    template: "AssistantPrompts.kt · DayReviewPrompt",
    statusKind: null,
    blind:
      "In-app by design. Deliberately NOT WhatsApp — a rep already gets pushes, calls, " +
      "CRM reminders, customer chats and founder requests. Coaching on top of that is noise. " +
      "Answers land in rep_prompts; the card itself is not a delivery event.",
    preview: `★★★★☆  8.5/10
48 calls · 37 connected · 2 visits fixed

🏆 What you did well
Good rapport — 2 site visits fixed today.

⚠️ One thing to fix
9 customers said "baad mein baat karte hain".
Say instead: "Sir kis din call karun? Main wahi time note kar leta hoon."

🎧 Best call · Sonu Aazmi · ★★★★★
📉 Sabse kamzor · Naseer Mohd · ★★

🎯 Kal sabse pehle
• Krishanpal Singh — feedback lena hai`,
  },
  {
    id: "push-hot-lead",
    audience: "telecaller",
    name: "Hot lead push",
    trigger: "DB trigger trg_notify_hot_lead when a lead turns hot",
    channel: "FCM push",
    sentBy: "notify-rep",
    template: "supabase/functions/notify-rep/index.ts",
    statusKind: null,
    blind:
      "Nothing is logged. notify-rep is fire-and-forget to FCM and writes no row, so there " +
      "is no way to prove a rep was told. Fixing this is the top recommendation in the " +
      "architecture review.",
    preview: `🔥 Hot lead — call now
Sonu Aazmi · Manas Property`,
  },
  {
    id: "push-assignment",
    audience: "telecaller",
    name: "Assignment push",
    trigger: "Triggers trg_notify_bulk_assign_ins / _upd",
    channel: "FCM push",
    sentBy: "notify-rep",
    template: "supabase/functions/notify-rep/index.ts",
    statusKind: null,
    blind: "Not logged — same fire-and-forget path as the hot-lead push.",
    preview: `📇 12 new leads assigned to you
Open Call Pro AI to start calling.`,
  },
  {
    id: "push-reminder",
    audience: "telecaller",
    name: "Reminder push",
    trigger: "Super admin presses Remind Rep in the Action Center",
    channel: "FCM push",
    sentBy: "RemindRep.tsx → notify-rep",
    template: "app/dashboard/actions/RemindRep.tsx",
    statusKind: "activity",
    preview: `Did they come to the site?
Sonu Aazmi — please record what happened at the visit.`,
  },

  // ─────────────────────────── CUSTOMER ───────────────────────────
  {
    id: "customer-manual",
    audience: "customer",
    name: "Rep's own WhatsApp",
    trigger: "Rep taps WhatsApp on a lead",
    channel: "Device WhatsApp",
    sentBy: "waTemplate() · opens the rep's own WhatsApp",
    template: "TelecallerScreens.kt · waTemplate()",
    statusKind: null,
    blind:
      "Sent from the rep's personal WhatsApp, so the CRM never sees it. Not a gap that can " +
      "be closed without routing customer messages through the platform.",
    preview: `Namaste Sonu ji, main Shweta bol rahi hoon Manas Property se.
Aapne humari property ke baare mein enquiry ki thi.`,
  },
  {
    id: "customer-inbox",
    audience: "customer",
    name: "Team Inbox reply",
    trigger: "Admin types a reply on the WhatsApp page",
    channel: "WhatsApp",
    sender: "Meta Cloud API only — never Baileys",
    sentBy: "whatsapp-send",
    template: "typed by hand, or an approved Meta template",
    statusKind: "wa:inbox",
    caveat:
      "The only entry here sent by a person rather than a schedule. Replies sent before the " +
      "Automation Center existed were not tagged, so \"never sent\" here means nobody has " +
      "replied since — not that the inbox has never been used. See the full thread history in " +
      "the Team Inbox.",
    livePreview: { href: "/dashboard/whatsapp", label: "Open Team Inbox" },
    preview: `(free text, or an approved template when outside the 24-hour window)`,
  },
];

export const AUDIENCE_LABEL: Record<Audience, string> = {
  founder: "Founder",
  telecaller: "Telecaller",
  customer: "Customer",
};

export const AUDIENCE_NOTE: Record<Audience, string> = {
  founder:
    "Business-critical only. The founder should not have to open the CRM — and should not be " +
    "messaged about anything that is not money or a customer standing on the site.",
  telecaller:
    "The rep's day already contains pushes, calls, reminders, customer chats and founder " +
    "requests. Coaching stays inside the app so it does not compete with all of that.",
  customer:
    "Never sent over Baileys. Customers are only ever messaged on the official Cloud API or " +
    "from the rep's own phone — an unofficial account carrying customer traffic risks the " +
    "number leads reply to.",
};
