/**
 * Every automated message this product sends, in one list.
 *
 * This file is the answer to "which message goes to whom", and it exists
 * because that answer was previously spread across nine edge functions, four
 * database triggers, nineteen crons and a Kotlin view-model — so the only way
 * to know whether the booking alert had fired was to read source and then
 * query the database by hand.
 *
 * It is deliberately a hand-maintained registry rather than something derived
 * from the code. There is no honest way to introspect "what does this cron
 * eventually send"; pretending otherwise would produce a screen that is
 * confidently wrong. A stale entry here is visible and fixable — a missing one
 * is a message nobody is watching, so ADD TO THIS LIST when you add a message.
 *
 * THIRTEEN entries, and the SHAPE is the point. The founder's four are four because
 * a fifth is what gets the number muted; the telecaller's seven stay split
 * across WhatsApp, push and in-app on purpose. Anyone adding another has to
 * add it here, in front of the list it is joining, which is the cheapest review
 * this codebase has.
 *
 * `statusKind` is how a row finds its own history:
 *   wa:<kind>   → whatsapp_messages.kind, stamped by _shared/notify.ts
 *   activity    → lead_activities, for reminders
 *   null        → nothing is recorded anywhere (see `blind`)
 */

export type Audience = "founder" | "telecaller" | "customer";

/** The four pipes, named once. Nothing else in the UI may invent a fifth. */
export type Transport = "baileys" | "meta" | "fcm" | "in-app" | "device";

/** The things that can be fired on demand without it being the real event. */
export type TestKind = "pulse" | "alert" | "rep" | "rep-weekly";

export const TRANSPORT: Record<Transport, { label: string; short: string; colour: string }> = {
  baileys: { label: "Baileys — the platform's own WhatsApp account", short: "Baileys", colour: "#25D366" },
  meta: { label: "Meta Cloud API — the official business number", short: "Meta Cloud API", colour: "#0866FF" },
  fcm: { label: "Firebase push to the rep's phone", short: "FCM push", colour: "#f59e0b" },
  "in-app": { label: "Shown inside the Android app", short: "In-app", colour: "#a78bfa" },
  device: { label: "The rep's own WhatsApp, on their own phone", short: "Device WhatsApp", colour: "#94a3b8" },
};

/** One hop in the journey from "something happened" to "it arrived". */
export type Step = string;

export type Automation = {
  id: string;
  audience: Audience;
  name: string;
  /** What makes it fire, in words a person can check. */
  trigger: string;
  /** Who it lands on. Counted live where the count is knowable. */
  recipient: string;
  transport: Transport;
  /** The function or file that sends it. */
  sentBy: string;
  /** Where the words live. */
  template: string;
  /**
   * Every hop, in order, ending at the transport. Rendered as the path the
   * user asked for: Lead → founder-alerts → notify.ts → Baileys → Delivered.
   * The final "Delivered" or "FAILED" is added from live data, not from here.
   */
  path: Step[];
  /** How this row finds its last send. */
  statusKind: string | null;
  /** Set when nothing at all is logged — stated rather than hidden. */
  blind?: string;
  /** A truth about the status line that would otherwise mislead. */
  caveat?: string;
  /** Safe ways to fire one now. Preview never sends; send really sends. */
  test?: { preview: TestKind | null; send: TestKind | null; note: string };
  /** The message as it actually reads. Kept beside the template path so the
   *  two are corrected together. */
  preview: string;
  /** Where a live, real-data preview already exists. */
  livePreview?: { href: string; label: string };
};

export const AUTOMATIONS: Automation[] = [
  // ─────────────────────────── FOUNDER ───────────────────────────
  // Four. Site visit fixed, booking, payment, and the daily report. A customer
  // who visited and has not been rung back used to be a fifth — it was cut, and
  // now lives on the Action Center where the person who chases it can see it.
  {
    id: "alert-site-visit-fixed",
    audience: "founder",
    name: "Site Visit Fixed",
    trigger: "A lead gets a site_visit_at in the future · swept every 15 min",
    recipient: "Every alerts-on recipient on Daily Pulse",
    transport: "baileys",
    sentBy: "founder-alerts",
    template: "supabase/functions/founder-alerts/index.ts · findAlerts()",
    path: ["Lead gets a visit date", "founder-alerts", "founder_alerts claim", "notify.ts", "WhatsApp"],
    statusKind: "wa:alert",
    test: {
      preview: "alert",
      send: "alert",
      note: "Preview reads today's real leads and sends nothing. Send runs the sweep for real — it " +
        "ignores quiet hours but can never re-send a milestone that already went.",
    },
    preview: `📍 SITE VISIT FIXED

👤 Customer: Sonu Aazmi
👩 Executive: Shweta
📍 Project: Manas Property
📅 Visit: 5 Aug, 11:00 AM

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "alert-booking",
    audience: "founder",
    name: "Booking",
    trigger: "Lead status becomes booked · swept every 15 min",
    recipient: "Every alerts-on recipient on Daily Pulse",
    transport: "baileys",
    sentBy: "founder-alerts",
    template: "supabase/functions/founder-alerts/index.ts · findAlerts()",
    path: ["Lead marked booked", "founder-alerts", "founder_alerts claim", "notify.ts", "WhatsApp"],
    statusKind: "wa:alert",
    caveat:
      "Shares the wa:alert history with the other two alerts, because all three leave in one " +
      "message when they happen in the same fifteen minutes. Three bookings in a good hour is " +
      "still exactly one buzz.",
    preview: `🎉 BOOKING CONFIRMED

👤 Customer: Krishanpal Singh
👩 Executive: Shweta
📍 Project: Manas Property
💰 Booking amount: ₹50,000

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "alert-payment",
    audience: "founder",
    name: "Payment",
    trigger: "Status token_paid with an amount · swept every 15 min",
    recipient: "Every alerts-on recipient on Daily Pulse",
    transport: "baileys",
    sentBy: "founder-alerts",
    template: "supabase/functions/founder-alerts/index.ts · findAlerts()",
    path: ["Token recorded", "founder-alerts", "founder_alerts claim", "notify.ts", "WhatsApp"],
    statusKind: "wa:alert",
    preview: `🏆 PAYMENT RECEIVED

👤 Customer: Krishanpal Singh
👩 Executive: Shweta
📍 Project: Manas Property
💰 ₹2.5L

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "pulse-team",
    audience: "founder",
    name: "Daily Pulse",
    trigger: "Hourly cron; goes to recipients whose chosen hour is now (IST)",
    recipient: "Recipients on Daily Pulse with no telecaller set",
    transport: "baileys",
    sentBy: "pulse-broadcast",
    template: "pulseText() · supabase/functions/_shared/pulse.ts",
    path: ["Cron, on the hour", "pulse-broadcast", "buildCompany()", "notify.ts", "WhatsApp"],
    statusKind: "wa:pulse",
    test: {
      preview: "pulse",
      send: "pulse",
      note: "Preview builds tonight's real report and delivers it nowhere. Send puts it on the phone.",
    },
    livePreview: { href: "/dashboard/pulse", label: "See today's real text on Daily Pulse" },
    preview: `📊 Manas property · Daily Pulse
Tue, 4 Aug

🟢 Today
• Bookings: 1
• Token collected: ₹50,000
• Site visits fixed: 2
• Hot leads: 10
• Calls: 8 · connected 7 (88%) · 11m talk
• Visit rate: 29% of everyone talked to

━━━━━━━━━━━━━━━
👤 Shweta
8 calls | 7 (88%) connected | 🔥 10 hot | 🎉 1 booked ₹50,000
✅ Sonu Aazmi committed to a site visit within 2 days.
🔸 Krishanpal Singh has visited but no feedback yet.
🎯 Next: Naseer Mohd — 3:44 PM

Auto Generated by Call Pro AI • Executive Intelligence`,
  },

  // ────────────────────────── TELECALLER ──────────────────────────
  {
    id: "pulse-own",
    audience: "telecaller",
    name: "Own Daily Pulse",
    trigger: "Same hourly cron, for recipients with a telecaller set",
    recipient: "That one telecaller, their own numbers only",
    transport: "baileys",
    sentBy: "pulse-broadcast",
    template: "repText() · supabase/functions/_shared/pulse.ts",
    path: ["Cron, on the hour", "pulse-broadcast", "repText()", "notify.ts", "WhatsApp"],
    statusKind: "wa:pulse",
    test: {
      preview: "pulse",
      send: "pulse",
      note: "Their own day only — never the team roll-up.",
    },
    livePreview: { href: "/dashboard/pulse", label: "Per-rep card on Daily Pulse" },
    preview: `📊 Shweta | Daily Pulse | Tue, 4 Aug
Manas property

🟢 Today
• Bookings: 0
• Site visits fixed: 2
• Hot leads: 10
• Calls: 8 · connected 7 (88%) · 11m talk

🎯 Biggest win
✅ Sonu Aazmi committed to a site visit within 2 days.

🎯 Priority next
• Naseer Mohd — 3:44 PM

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "rep-daily-review",
    audience: "telecaller",
    name: "Daily Sales Review",
    trigger: "Hourly cron, at each company's review hour (7pm IST by default)",
    recipient: "Every active telecaller with a phone number, in every company",
    transport: "baileys",
    sentBy: "pulse-broadcast → sendRepReviews()",
    template: "repReviewText() · supabase/functions/_shared/pulse.ts",
    path: ["7pm IST", "pulse-broadcast", "rep_day_score()", "notify.ts", "WhatsApp"],
    statusKind: "wa:rep_review",
    test: {
      preview: "rep",
      send: "rep",
      note: "Preview builds today's real review for one rep and sends nothing.",
    },
    caveat:
      "Enrolment is DERIVED, not a list: every active telecaller with a phone number is in, " +
      "automatically, the day they are created. Which is also the catch — 8 of 9 telecallers " +
      "currently have no phone number on their profile, so they are enrolled in nothing. The " +
      "Salespeople page is where that is fixed.",
    preview: `📊 Today's Sales Review
Shweta · Manas property · Tue, 4 Aug

Score: 42/100

✅ You completed 6 follow-ups.
⚠️ 3 follow-ups were missed.
⚠️ 41 customers are still waiting from earlier days.
📞 18 calls connected · 24m talk.

📈 Score built from
• Follow-ups kept — 6 of 9
• Calls connected — 18 connected
• Calls with a note or next step — 12 of 18

🎯 Tomorrow's mission
Clear the 3 missed follow-ups before 11 AM.

Keep going — you can improve this tomorrow.

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "rep-weekly-review",
    audience: "telecaller",
    name: "Weekly Review",
    trigger: "Monday 10am IST, about the week just finished",
    recipient: "The same derived list as the daily review",
    transport: "baileys",
    sentBy: "pulse-broadcast → sendRepReviews()",
    template: "repWeeklyText() · supabase/functions/_shared/pulse.ts",
    path: ["Monday 10am", "pulse-broadcast", "rep_week_summary()", "notify.ts", "WhatsApp"],
    statusKind: "wa:rep_weekly",
    test: {
      preview: "rep-weekly",
      send: "rep-weekly",
      note: "Preview builds last week's real numbers for one rep and sends nothing.",
    },
    caveat:
      "Strongest and weakest are the best and worst SCORED component of the week — measured, " +
      "not named. \"Best skill: handling objections\" needs the call recordings put through the " +
      "coaching brain; 645 transcripts exist, so it is buildable, but naming a skill nobody " +
      "measured is the same mistake as scoring the notes column nobody fills.",
    preview: `📅 Weekly Review
Ankita · Fanbe
28 Jul – 03 Aug

Average score: 58/100

🟢 The week
📞 Calls: 801 · 477 connected · 9h 57m talk
🔁 Follow-ups: 132 of 130 kept
📍 Site visits: 7
🎉 Bookings: 0

💪 Strongest this week
Calls connected — 90% of the time

📈 Needs improvement
New leads called in 2h — 30% of the time

No bookings yet this week. The site visits are where they come from.

Auto Generated by Call Pro AI • Executive Intelligence`,
  },
  {
    id: "push-hot-lead",
    audience: "telecaller",
    name: "Hot Lead Push",
    trigger: "DB trigger trg_notify_hot_lead, the moment a lead turns hot",
    recipient: "The rep the lead is assigned to",
    transport: "fcm",
    sentBy: "notify-rep",
    template: "supabase/functions/notify-rep/index.ts",
    path: ["Lead turns hot", "trg_notify_hot_lead", "notify-rep", "Firebase", "Rep's phone"],
    statusKind: null,
    blind:
      "Nothing is logged. notify-rep is fire-and-forget to Firebase and writes no row, so there " +
      "is no way to prove a rep was told — the phone either buzzed or it did not, and the CRM " +
      "cannot say which. This is the biggest remaining hole in the Automation Center and the top " +
      "recommendation in the architecture review.",
    preview: `🔥 Hot lead — call now
Sonu Aazmi · Manas Property`,
  },
  {
    id: "push-assignment",
    audience: "telecaller",
    name: "Assignment Push",
    trigger: "Triggers trg_notify_bulk_assign_ins / _upd, on assignment",
    recipient: "The rep receiving the leads",
    transport: "fcm",
    sentBy: "notify-rep",
    template: "supabase/functions/notify-rep/index.ts",
    path: ["Leads assigned", "trg_notify_bulk_assign", "notify-rep", "Firebase", "Rep's phone"],
    statusKind: null,
    blind: "Not logged — same fire-and-forget path as the hot-lead push.",
    preview: `📇 12 new leads assigned to you
Open Call Pro AI to start calling.`,
  },
  {
    id: "push-reminder",
    audience: "telecaller",
    name: "Reminder Push",
    trigger: "A human presses Remind Rep in the Action Center",
    recipient: "The rep who owns that lead",
    transport: "fcm",
    sentBy: "RemindRep.tsx → notify-rep",
    template: "app/dashboard/actions/RemindRep.tsx",
    path: ["Someone presses Remind Rep", "notify-rep", "Firebase", "Rep's phone", "lead_activities"],
    statusKind: "activity",
    caveat:
      "The only telecaller push with a record, and the record is the lead_activities row written " +
      "alongside it — not proof the phone buzzed. It says a human asked, not that the rep saw it.",
    preview: `Did they come to the site?
Sonu Aazmi — please record what happened at the visit.`,
  },
  {
    id: "rep-coach",
    audience: "telecaller",
    name: "Rep Coach — 7pm review",
    trigger: "Assistant tick after the review hour, once a day",
    recipient: "The rep, on their own screen",
    transport: "in-app",
    sentBy: "rep-coach → AssistantPrompts.kt",
    template: "AssistantPrompts.kt · DayReviewPrompt",
    path: ["7pm, rep has the app open", "rep-coach", "AssistantPrompts.kt", "Card in the app"],
    statusKind: null,
    blind:
      "In-app by design, and it stays that way. A rep already gets pushes, calls, CRM reminders, " +
      "customer chats and founder requests; coaching delivered on top of that is not help, it is " +
      "one more thing to swipe away. Answers land in rep_prompts — but the card being shown is " +
      "not a delivery event, so there is no send to report here.",
    preview: `★★★★☆  8.5/10
48 calls · 37 connected · 2 visits fixed

🏆 What you did well
Good rapport — 2 site visits fixed today.

⚠️ One thing to fix
9 customers said "baad mein baat karte hain".
Say instead: "Sir kis din call karun? Main wahi time note kar leta hoon."

🎧 Best call · Sonu Aazmi · ★★★★★
📉 Weakest call · Naseer Mohd · ★★

🎯 First thing tomorrow
• Krishanpal Singh — get the feedback`,
  },

  // ─────────────────────────── CUSTOMER ───────────────────────────
  {
    id: "customer-inbox",
    audience: "customer",
    name: "Team Inbox reply",
    trigger: "An admin types a reply on the WhatsApp page",
    recipient: "The customer",
    transport: "meta",
    sentBy: "whatsapp-send",
    template: "typed by hand, or an approved Meta template",
    path: ["Admin types a reply", "whatsapp-send", "Meta Cloud API", "Customer's WhatsApp"],
    statusKind: "wa:inbox",
    caveat:
      "Sent by a person, not a schedule — it is here because it is the one automated-looking path " +
      "that touches a customer, and the transport must stay visible. Replies sent before the " +
      "Automation Center existed were not tagged, so \"never sent\" means nobody has replied " +
      "since, not that the inbox has never been used.",
    livePreview: { href: "/dashboard/whatsapp", label: "Open Team Inbox" },
    preview: `(free text, or an approved template when outside the 24-hour window)`,
  },
  {
    id: "customer-manual",
    audience: "customer",
    name: "Rep's personal WhatsApp",
    trigger: "Rep taps WhatsApp on a lead in the Android app",
    recipient: "The customer",
    transport: "device",
    sentBy: "waTemplate() · opens the rep's own WhatsApp",
    template: "TelecallerScreens.kt · waTemplate()",
    path: ["Rep taps WhatsApp", "waTemplate()", "Rep's own phone", "Customer's WhatsApp"],
    statusKind: null,
    blind:
      "Leaves from the rep's personal WhatsApp, so the CRM never sees it and cannot. Not a gap " +
      "that can be closed without routing customer conversations through the platform.",
    preview: `Namaste Sonu ji, main Shweta bol rahi hoon Manas Property se.
Aapne humari property ke baare mein enquiry ki thi.`,
  },
];

export const AUDIENCE_LABEL: Record<Audience, string> = {
  founder: "Founder",
  telecaller: "Telecaller",
  customer: "Customer",
};

export const AUDIENCE_NOTE: Record<Audience, string> = {
  founder:
    "Four messages, and four is a decision. Site visit fixed, booking, payment, and the daily " +
    "report — everything else is in the Pulse or on the Action Center. A founder who gets pinged " +
    "for every lead movement mutes the number within a week, and then the one booking alert that " +
    "mattered arrives silently.",
  telecaller:
    "The rep's day already contains pushes, calls, reminders, customer chats and founder " +
    "requests. Coaching stays inside the app so it does not compete with all of that, and only " +
    "the two Pulse-style messages ever reach WhatsApp.",
  customer:
    "Never Baileys. Customers are only ever messaged on the official Cloud API or from the rep's " +
    "own phone — an unofficial account carrying customer traffic risks a ban on the number leads " +
    "reply to, and losing that costs the business rather than an evening.",
};

/** The transport map, stated once so there is no ambiguity anywhere. */
export const ROUTING: Array<{ what: string; transport: Transport; why: string }> = [
  {
    what: "Founder alerts + Daily Pulse",
    transport: "baileys",
    why: "Internal reporting to a number we control. No 24-hour window, no templates, no token to expire.",
  },
  {
    what: "Telecaller's own Pulse",
    transport: "baileys",
    why: "Same pipe, same reason — a rep is internal, not a customer.",
  },
  {
    what: "Team Inbox → customer",
    transport: "meta",
    why: "The only account with a business agreement behind it. Customer traffic on Baileys risks the ban.",
  },
  {
    what: "Rep's chat with a lead",
    transport: "device",
    why: "Opens the rep's own WhatsApp. Never touches a platform number at all.",
  },
];
